"""tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-12 23:39:27.727489

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_ts'), 'audit_events', ['ts'], unique=False)
    op.create_table('case_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_index('ix_case_events_case_seq', 'case_events', ['case_id', 'seq'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_id', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('effort', sa.String(length=8), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('failure_class', sa.String(length=16), nullable=True),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('halt_reason', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.BigInteger(), nullable=False),
    sa.Column('tokens_out', sa.BigInteger(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('spend_usd', sa.Float(), nullable=False),
    sa.Column('evidence_counter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_id')
    )
    op.create_index(op.f('ix_cases_fingerprint'), 'cases', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('chat_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('context_case_id', sa.String(length=36), nullable=True),
    sa.Column('promoted_case_id', sa.String(length=36), nullable=True),
    sa.Column('budget_date', sa.String(length=10), nullable=False),
    sa.Column('spend_usd_today', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=12), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('default_branch', sa.String(length=64), nullable=False),
    sa.Column('credential_env', sa.String(length=64), nullable=False),
    sa.Column('watch', sa.Boolean(), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('poll_cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repos_provider_slug', 'repos', ['provider', 'slug'], unique=True)
    op.create_table('runbooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('source_case_id', sa.String(length=36), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('structured', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('body_edited_md', sa.Text(), nullable=True),
    sa.Column('verification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_id', sa.String(length=96), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_case_id'), 'artifacts', ['case_id'], unique=False)
    op.create_table('case_learnings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('signal_signature', sa.Text(), nullable=False),
    sa.Column('confirmed_root_cause', sa.Text(), nullable=False),
    sa.Column('decisive_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('false_leads', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_ledger', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('eid', sa.String(length=8), nullable=False),
    sa.Column('worker', sa.String(length=24), nullable=False),
    sa.Column('toolset', sa.String(length=48), nullable=False),
    sa.Column('invocation', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('hypothesis_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_case_eid', 'evidence', ['case_id', 'eid'], unique=True)
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('hid', sa.String(length=8), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_for', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_against', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hypotheses_case_hid', 'hypotheses', ['case_id', 'hid'], unique=True)
    op.create_index(op.f('ix_hypotheses_case_id'), 'hypotheses', ['case_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('reporter', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('attach_reason', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_case_id'), 'signals', ['case_id'], unique=False)
    op.create_index(op.f('ix_signals_fingerprint'), 'signals', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_signals_received_at'), 'signals', ['received_at'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('gate', sa.String(length=12), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('annotation', sa.Text(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_case_id'), 'approvals', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_case_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_signals_received_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_fingerprint'), table_name='signals')
    op.drop_index(op.f('ix_signals_case_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_hypotheses_case_id'), table_name='hypotheses')
    op.drop_index('ix_hypotheses_case_hid', table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_index('ix_evidence_case_eid', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('case_learnings')
    op.drop_index(op.f('ix_artifacts_case_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('settings')
    op.drop_table('runbooks')
    op.drop_index('ix_repos_provider_slug', table_name='repos')
    op.drop_table('repos')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_fingerprint'), table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_case_events_case_seq', table_name='case_events')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_audit_events_ts'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
